return {
    --Home
    ["UPLOAD"] = "上传",
    ["DELETE"] = "删除",
    ["EXECUTE"] = "注入",
    ["Keyboard"] = "键盘",
    ["Built-In"] = "内置",
    --Executor
    ["Network"] = "网络",
    ["Client status information"] = "客户端状态",
    ["Check out this script!"] = "看看这个脚本!",
    ["an admin script dedicated to provide the necessities of exploiting."] = "一个专为脚本开发者的管理脚本",
    ["CLEAR"] = "清空",
    ["EXECUTE CLIPBOARD"] = "从剪贴板注入",
    --Setting
    ["Enabled"] = "已启用",
    ["Disabled"] = "已禁用",
    ["All"] = "全部",
    ["Search for options"] = "搜索功能",
    ["Anti Scam"] = "防诈骗",
    ["Enable protection for your Robux and in-game items."] = "保护你的Robux和游戏内物品",
    ["Disable Robux"] = "禁用Robux",
    ["Block all ROBUX purchases making it impossible to lose ROBUX to scams"] = "阻止所有ROBUX交易，防止被骗",
    ["Verify Teleports"] = "验证传送",
    ["Only allow teleports to the same place id"] = "仅允许传送到相同的Place ID",
    ["Auto Execute"] = "自动执行",
    ["Toggle auto-execution of scripts in the autoexec folder"] = "允许autoexec文件夹中脚本的自动注入",
    ["Anti AFK"] = "防挂机",
    ["Disable all idle timeout kicks from the source"] = "禁用所有因挂机导致的踢出",
    ["Auto Close"] = "自动关闭",
    ["Toggle X button requirement to close popups"] = "切换关闭弹窗是否需要点击X按钮",
    ["Console"] = "控制台",
    ["Toggle roblox console logs in the GUI"] = "在界面中显示/隐藏Roblox控制台日志",
    ["Join Discord"] = "加入Discord",
    ["Copies our discord invite"] = "复制我们的Discord邀请链接",
    ["CLICK HERE"] = "点击这里",
    ["Rejoin"] = "重进",
    ["Rejoins your current server"] = "重新进入当前服务器",
    ["Small Server"] = "小型服务器",
    ["Joins a server with a low playercount"] = "加入人数少服务器",
    ["Serverhop"] = "换服",
    ["Teleport to a new server"] = "传送到新服务器",
    ["FPS Cap"] = "FPS上限",
    ["Change the FPS cap for a smoother experience"] = "设置FPS上限以获得更流畅体验",
    ["Icon Size"] = "图标大小",
    ["Change the floating Icon's size"] = "修改悬浮图标的大小",
    ["Small"] = "小",
    ["Medium"] = "中",
    ["Large"] = "大",
    ["Icon Shape"] = "图标形状",
    ["Change the floating Icon's shape"] = "修改悬浮图标的形状",
    ["Squircle"] = "圆角方形",
    ["Circle"] = "圆形",
    ["Square"] = "方形",
    ["Icon Color"] = "图标颜色",
    ["Change the floating Icon's color"] = "修改悬浮图标的颜色",
    ["Blue"] = "蓝色",
    ["Green"] = "绿色",
    ["Purple"] = "紫色",
    --Console
    ["Roblox Console"] = "Roblox 控制台",
    ["Console that get outputs from ROBLOX console and display it in this menu."] = "获取ROBLOX控制台中的输出并在菜单中显示",
    ["Search:"] = "搜索:",
    ["Delta Console"] = "Delta 控制台",
    ["Console that provides output, input from Delta API."] = "提供来自Delta API的输入输出功能",
}
